import { useEffect, useRef, useState } from 'react';
import { ArrowUp, Check, ChevronRight, Mic, MicOff, ShieldAlert, Volume2, VolumeX, Waves, X } from 'lucide-react';
import { ATOM_AGENT_MODEL, type AgentApprovalRequest, type AgentConnectionState, type AgentMessage, type AgentStatus, type AtomRealtimeRateLimit, type AtomRealtimeUsage } from '@tinysa/agent';
import type { InstrumentSessionProvenance } from '@tinysa/contracts';
import { AtomicMark } from './AtomicMark.js';

export function AtomAgentPanel({open,state,status,messages,approval,execution,microphoneMuted,speakerMuted,usage,rateLimits,onClose,onSend,onVoice,onMicrophoneMute,onSpeakerMute,onApproval}:{
  open:boolean;state:AgentConnectionState;status?:AgentStatus;messages:readonly AgentMessage[];approval?:AgentApprovalRequest;
  execution?:InstrumentSessionProvenance['execution'];microphoneMuted:boolean;speakerMuted:boolean;usage?:AtomRealtimeUsage;rateLimits?:readonly AtomRealtimeRateLimit[];
  onClose():void;onSend(text:string):void;onVoice():void;onMicrophoneMute(muted:boolean):void;onSpeakerMute(muted:boolean):void;onApproval(approved:boolean):void;
}){
  const [input,setInput]=useState('');const [collapsed,setCollapsed]=useState(false);const end=useRef<HTMLDivElement>(null);useEffect(()=>{if(!collapsed&&typeof end.current?.scrollIntoView==='function')end.current.scrollIntoView({block:'end'});},[messages,approval,collapsed]);
  if(!open)return null;
  const voiceActive=['connecting','listening','thinking','speaking'].includes(state);
  const voiceConnected=['listening','thinking','speaking'].includes(state);
  const tokenRate=rateLimits?.find(limit=>limit.name==='tokens');
  const tokenRateLabel=tokenRate&&tokenRate.limit!==undefined&&tokenRate.remaining!==undefined?`TPM ${compact(tokenRate.limit-tokenRate.remaining)}/${compact(tokenRate.limit)}`:undefined;
  const tokenRateTitle=tokenRateLabel?`${tokenRateLabel}${tokenRate?.resetSeconds===undefined?'':` · resets in ${tokenRate?.resetSeconds.toFixed(1)}s`}${usage?` · last response ${usage.totalTokens.toLocaleString()} tokens (${usage.cachedTokens.toLocaleString()} cached)`:''}`:undefined;
  function submit(){if(input.trim()){onSend(input);setInput('');}}
  return <aside className={`atom-panel ${collapsed?'collapsed':''}`} aria-label="Atom AI copilot">
    <button type="button" data-agent-exclusion="human-agent-boundary" className="atom-grabber" onClick={()=>setCollapsed(value=>!value)} aria-label={collapsed?'Expand Atom':'Collapse Atom'} aria-expanded={!collapsed}><span/></button>
    <div className="atom-head"><button type="button" data-agent-exclusion="human-agent-boundary" className="atom-identity" onClick={()=>setCollapsed(value=>!value)} aria-label={collapsed?'Expand Atom':'Collapse Atom'}><div className="atom-mark"><AtomicMark size={29} active={voiceActive}/></div><strong>Atom</strong><small className="atom-head-state">{voiceLabel(state)}</small></button><button data-agent-control="atom.close" className="icon-button" onClick={onClose} aria-label="Close Atom"><X size={17}/></button></div>
    <div className={`voice-stage state-${state} ${voiceActive?'active':''}`}><div className="voice-ambient" aria-hidden="true"><i/><i/><i/><span><AtomicMark size={24} active={voiceActive}/></span></div><div className="voice-stage-copy"><strong>{voiceLabel(state)}</strong>{!status?.configured?<span>OPENAI_KEY required</span>:<span>{voiceConnected?(microphoneMuted?'Connected · microphone muted':speakerMuted?'Connected · Atom audio muted':'Ballad · live duplex'):'Realtime voice offline'}</span>}<button data-agent-exclusion="human-agent-boundary" className="voice-session-action" onClick={onVoice} disabled={!status?.configured}>{voiceActive?'Disconnect':'Connect'}</button></div><div className="voice-io-controls"><button data-agent-control="atom.microphone-mute" data-agent-exclusion="human-agent-boundary" className={`${microphoneMuted?'muted':'live'} ${voiceConnected?'connected':'disconnected'}`} disabled={!voiceConnected} onClick={()=>onMicrophoneMute(!microphoneMuted)} aria-label={microphoneMuted?'Unmute microphone':'Mute microphone'} title={microphoneMuted?'Connected · microphone muted':'Connected · microphone live'}>{microphoneMuted?<MicOff size={14}/>:<Mic size={14}/>}</button><button data-agent-control="atom.speaker-mute" data-agent-exclusion="human-agent-boundary" className={`${speakerMuted?'muted':'live'} ${voiceConnected?'connected':'disconnected'} ${state==='speaking'?'speaking':''}`} disabled={!voiceConnected} onClick={()=>onSpeakerMute(!speakerMuted)} aria-label={speakerMuted?'Unmute Atom audio':'Mute Atom audio'} title={speakerMuted?'Connected · speaker muted':'Connected · speaker live'}>{speakerMuted?<VolumeX size={14}/>:<Volume2 size={14}/>}</button></div></div>
    <div className="atom-messages">{messages.map(message=><div key={message.id} className={`atom-message ${message.role} ${message.status??''}`}><span>{message.role==='assistant'?<AtomicMark size={14}/>:message.role==='tool'?<Check size={12}/>:message.role==='system'?<ShieldAlert size={12}/>:null}</span><p>{message.text}</p></div>)}
      {approval&&<div className="approval-card"><div><ShieldAlert size={17}/><span><strong>Approval required</strong><small>{execution==='physical'?'PHYSICAL INSTRUMENT ACTION':execution==='firmware-executed-twin'?'FIRMWARE TWIN ACTION':execution==='signal-lab-simulation'?'SIGNALLAB ACTION':'EXECUTION BACKEND ACTION'}</small></span></div><p>{approval.summary}. {execution==='physical'?(approval.tool==='set_rf_output'?'Confirm only after checking the connected load and attenuation.':'The firmware UI may expose physical RF-output controls; verify screen state before proceeding.'):execution==='firmware-executed-twin'?'This action changes executable firmware state but cannot radiate through the Renode bridge.':execution==='signal-lab-simulation'?'SignalLab exposes no RF, screen, or USB action capability.':'The target execution is unavailable.'}</p><div><button data-agent-exclusion="human-approval-boundary" onClick={()=>onApproval(false)}>Deny</button><button data-agent-control="atom.approve-high-impact" data-agent-risk="high-impact" data-agent-exclusion="human-approval-boundary" className="approve" onClick={()=>onApproval(true)}>Approve action</button></div></div>}
      <div ref={end}/>
    </div>
    {!messages.some(message=>message.role==='user')&&<div className="atom-prompts"><button data-agent-exclusion="human-agent-boundary" onClick={()=>onSend('Set up an FM broadcast band sweep and explain what I should look for.')}><Waves size={14}/><strong>Survey the FM band</strong><ChevronRight size={14}/></button><button data-agent-exclusion="human-agent-boundary" onClick={()=>onSend('Inspect the current instrument state and tell me if anything looks unsafe or inconsistent.')}><ShieldAlert size={14}/><strong>Run a safety check</strong><ChevronRight size={14}/></button></div>}
    <div className="atom-composer"><textarea data-agent-exclusion="human-agent-boundary" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}}} placeholder={status?.configured?'Ask Atom anything about this RF session…':'OPENAI_KEY required'} disabled={!status?.configured}/><button data-agent-exclusion="human-agent-boundary" onClick={submit} disabled={!status?.configured||!input.trim()} aria-label="Send to Atom"><ArrowUp size={16}/></button></div>
    <div className="atom-foot"><span><i className={status?.configured?'online':''}/>{state.toUpperCase()}</span><span title={tokenRateTitle}>{tokenRateLabel?`${tokenRateLabel} · `:''}{ATOM_AGENT_MODEL} · {status?.voice.toUpperCase()??'NO VOICE'} · {status?.reasoningEffort?.toUpperCase()??'NO REASONING'}</span></div>
  </aside>;
}
function voiceLabel(state:AgentConnectionState){return state==='connecting'?'Connecting…':state==='listening'?'Listening':state==='thinking'?'Thinking':state==='speaking'?'Speaking':state==='unconfigured'?'Not configured':state==='error'?'Needs attention':'Start voice';}
function compact(value:number){return value>=1_000?`${(value/1_000).toFixed(value>=10_000?0:1)}K`:Math.round(value).toString();}
