import { ArrowRight, BrainCircuit, CheckCircle2, Database, Fingerprint, ShieldQuestion, Sparkles } from 'lucide-react';
import type { DetectedSignal, Sweep } from '@tinysa/contracts';
import { formatFrequency, formatLevel } from '../format.js';

export function ClassificationWorkspace({ sweep, detections }: { sweep?: Sweep; detections: readonly DetectedSignal[] }) {
  return <div className="classification-grid"><section className="pipeline-panel"><div className="panel-header"><div><Sparkles size={14}/>CLASSIFICATION PIPELINE</div><span className="lab-badge">MODEL REQUIRED</span></div><div className="pipeline"><PipelineStep icon={<Database/>} label="Capture" detail={sweep?`${sweep.frequencyHz.length} bins ready`:'Awaiting sweep'} ready={Boolean(sweep)}/><ArrowRight/><PipelineStep icon={<Fingerprint/>} label="Detect" detail={`${detections.length} candidate${detections.length===1?'':'s'}`} ready={detections.length>0}/><ArrowRight/><PipelineStep icon={<BrainCircuit/>} label="Classify" detail="No model installed" ready={false}/></div></section>
    <section className="classification-result"><div className="result-empty"><div className="unknown-orbit"><ShieldQuestion size={34}/><span/><span/></div><span className="section-kicker">OPEN-SET RESULT</span><h2>Unknown by design</h2><p>The control plane will not infer waveform labels until a validated local model, taxonomy, and calibration profile are installed.</p><div className="model-gate">LOCAL MODEL REQUIRED</div></div><div className="evidence-card"><div className="evidence-head"><span>EVIDENCE CONTRACT</span><CheckCircle2 size={15}/></div><ul><li><span>01</span>Source sweep and device provenance</li><li><span>02</span>Ranked candidates with calibrated confidence</li><li><span>03</span>Open-set rejection and explicit unknown</li><li><span>04</span>Model and preprocessing identity</li></ul></div></section>
    <section className="candidate-panel"><div className="panel-header"><span>DETECTION CANDIDATES</span><span>{detections.length} AVAILABLE</span></div>{detections.length?<div className="candidate-list">{detections.map((d)=><div className="candidate-row" key={d.id}><span className="candidate-index">{d.id.split(':').at(-1)?.padStart(2,'0')}</span><span><strong>{formatFrequency(d.peakHz)}</strong><small>{formatFrequency(d.bandwidthHz)} · {formatLevel(d.peakDbm)}</small></span><em>UNKNOWN</em></div>)}</div>:<div className="table-empty"><Fingerprint size={20}/><strong>No candidates to classify</strong><span>Run an acquisition from Spectrum or Detection.</span></div>}</section>
  </div>;
}
function PipelineStep({icon,label,detail,ready}:{icon:React.ReactNode;label:string;detail:string;ready:boolean}){return <div className={`pipeline-step ${ready?'ready':''}`}><span>{icon}</span><div><strong>{label}</strong><small>{detail}</small></div>{ready&&<CheckCircle2 size={14}/>}</div>}
