import { ChevronsUp, RadioTower } from 'lucide-react';
import type { DetectedSignal, SignalDetectionConfig, Sweep } from '@tinysa/contracts';
import { formatFrequency, formatLevel, median } from '../format.js';
import { SpectrumPlot } from './SpectrumPlot.js';

export function DetectionWorkspace({ sweep, detections, busy, config, onConfig }: { sweep?: Sweep; detections: readonly DetectedSignal[]; busy: boolean; config: SignalDetectionConfig; onConfig(config: SignalDetectionConfig): void }) {
  const floor = sweep ? median(sweep.powerDbm) : Number.NaN;
  return <div className="analysis-layout"><div className="analysis-main"><SpectrumPlot sweep={sweep} detections={detections} busy={busy}/><section className="event-panel"><div className="panel-header"><div><RadioTower size={14}/>DETECTED EMISSIONS <span className="count-badge">{detections.length}</span></div><span>SWEEP-LOCAL</span></div>{detections.length ? <div className="event-table" role="table"><div className="event-row table-head" role="row"><span>STATUS</span><span>PEAK</span><span>POWER</span><span>BANDWIDTH</span><span>AGE</span></div>{detections.map((item,i)=><div className="event-row" role="row" key={item.id}><span><i className="signal-pulse"/>ACTIVE {String(i+1).padStart(2,'0')}</span><strong>{formatFrequency(item.peakHz)}</strong><span>{formatLevel(item.peakDbm)}</span><span>{formatFrequency(item.bandwidthHz)}</span><span>NOW</span></div>)}</div> : <div className="table-empty"><ChevronsUp size={20}/><strong>Waiting for detectable energy</strong><span>Acquire a sweep to evaluate the configured threshold.</span></div>}</section></div>
    <aside className="analysis-inspector"><div className="inspector-head"><span>DETECTOR</span><em>ACTIVE</em></div><div className="detector-visual"><div className="floor-line"><span style={{width:sweep?'68%':'0%'}}/></div><div><small>ESTIMATED FLOOR</small><strong>{Number.isFinite(floor)?formatLevel(floor):'—'}</strong></div></div><div className="control-section"><span className="control-heading">THRESHOLD</span><div className="segmented"><button className={config.threshold.strategy==='noise-relative'?'active':''} onClick={()=>onConfig({...config,threshold:{strategy:'noise-relative',marginDb:10}})}>Adaptive</button><button className={config.threshold.strategy==='absolute'?'active':''} onClick={()=>onConfig({...config,threshold:{strategy:'absolute',levelDbm:-80}})}>Absolute</button></div>{config.threshold.strategy==='noise-relative'?<label><span>Margin above floor</span><div className="range-with-value"><input aria-label="Margin above floor" type="range" min="3" max="30" value={config.threshold.marginDb} onChange={(e)=>onConfig({...config,threshold:{strategy:'noise-relative',marginDb:Number(e.target.value)}})}/><output>+{config.threshold.marginDb} dB</output></div></label>:<label><span>Absolute level</span><div className="range-with-value"><input aria-label="Absolute threshold" type="range" min="-120" max="0" value={config.threshold.levelDbm} onChange={(e)=>onConfig({...config,threshold:{strategy:'absolute',levelDbm:Number(e.target.value)}})}/><output>{config.threshold.levelDbm} dBm</output></div></label>}<label><span>Minimum bandwidth</span><select value={config.minimumBandwidthHz} onChange={(e)=>onConfig({...config,minimumBandwidthHz:Number(e.target.value)})}><option value="0">Any width</option><option value="10000">10 kHz</option><option value="100000">100 kHz</option></select></label><div className="detector-status-row"><span>Persistence</span><output>1 sweep · local</output></div></div><div className="inspector-note amber"><span/>Cross-sweep tracking is not installed; every result is explicitly sweep-local.</div></aside>
  </div>;
}
