import { AlertTriangle, Power, Radio, ShieldCheck, Waves } from 'lucide-react';
import type { DeviceSnapshot, GeneratorConfig } from '@tinysa/contracts';
import { formatFrequency } from '../format.js';

export function GeneratorWorkspace({ config, snapshot, busy, onChange, onApply, onOutput }: { config: GeneratorConfig; snapshot: DeviceSnapshot; busy:boolean; onChange(config:GeneratorConfig):void; onApply():void; onOutput(enabled:boolean):void }) {
  const on = snapshot.generatorOutput==='on'; const ready=snapshot.connection==='ready';
  return <div className="generator-layout"><section className={`rf-stage ${on?'is-on':''}`}><div className="rf-halo"><Radio size={36}/><span/><span/><span/></div><span className="section-kicker">RF OUTPUT STATE</span><h2>{snapshot.generatorOutput.toUpperCase()}</h2><p>{on?'Energy may be present at the connected RF output.':'Output is commanded off. Software is not a physical interlock.'}</p><button data-agent-control="generator.rf-output" data-agent-risk="high-impact" className={`output-control ${on?'stop':'start'}`} disabled={!ready||busy} onClick={()=>onOutput(!on)}><Power size={17}/>{on?'Disable RF output':'Enable RF output'}</button></section>
    <section className="generator-controls"><div className="panel-header"><div><Waves size={14}/>OUTPUT CONFIGURATION</div><span>{snapshot.verification.toUpperCase()}</span></div><div className="generator-form"><label><span>Frequency</span><div className="large-input"><input type="number" value={config.frequencyHz} onChange={(e)=>onChange({...config,frequencyHz:Number(e.target.value)})}/><em>Hz</em></div><small>{formatFrequency(config.frequencyHz)}</small></label><label><span>Output level</span><div className="large-input"><input type="number" min="-115" max="-19" value={config.levelDbm} onChange={(e)=>onChange({...config,levelDbm:Number(e.target.value)})}/><em>dBm</em></div></label><label><span>Modulation</span><select value={config.modulation} onChange={(e)=>onChange({...config,modulation:e.target.value as GeneratorConfig['modulation']})}><option value="off">None</option><option value="am">AM</option><option value="nfm">Narrow FM</option><option value="wfm">Wide FM</option></select></label><button className="secondary full" disabled={!ready||busy||on} onClick={onApply}>Apply configuration</button></div></section>
    <section className="safety-panel"><div><ShieldCheck size={18}/><span><strong>Safety contract active</strong><small>Output never restores on reconnect</small></span></div><ul><li><AlertTriangle size={13}/>Verify attenuation and load before enabling.</li><li><AlertTriangle size={13}/>Cable loss makes actual RF state unknown.</li><li><AlertTriangle size={13}/>Input protection cannot be enforced in software.</li></ul></section></div>;
}
