/* Generated by tools/train-observable-classifier.ts; do not hand edit. */
export const BAYESIAN_OBSERVABLE_MODEL_SHA256 = '05ec69aacc100f272446b7e00ba36cd112e516b8832585174312bac1f6af7d0c' as const;
